'use strict';
process.env.NODE_ENV='test';
process.env.JWT_ACCESS_SECRET='test-jwt-access-secret-32-chars-min!!';
process.env.RATE_LIMIT_MAX='100000';
const path=require('node:path');
module.paths.push(path.join(__dirname, '../../backend/node_modules'));
const mongoose=require('mongoose'), http=require('node:http'), jwt=require('jsonwebtoken');
const {createApp}=require('../../backend/src/server');
const {seedLoadTestData,resetLoadTestData}=require('../scripts/seedLoadTestData');
const {User}=require('../../backend/src/models/User');
const {Session}=require('../../backend/src/models/Session');
const {MenuItem}=require('../../backend/src/models/MenuItem');
async function run(){
  await mongoose.connect('mongodb://127.0.0.1:27017/zamorin_loadtest',{maxPoolSize:20});
  await resetLoadTestData(); await seedLoadTestData();
  const PORT=4997;
  const allowedOrigins=['http://127.0.0.1:'+PORT];
  const app=createApp({production:false,test:true,allowedOrigins});
  const server=http.createServer(app);
  await new Promise(r=>server.listen(PORT,'127.0.0.1',r));
  const secret='test-jwt-access-secret-32-chars-min!!';
  const now=new Date();
  const ds=now.toISOString().slice(0,10).replace(/-/g,'');
  const admin=await User.findOne({organisationId:'LOADTEST_ORG',role:'CAFE_ADMIN'}).lean();
  const item=await MenuItem.findOne({organisationId:'LOADTEST_ORG'}).lean();
  const sid='SS-'+ds+'-99003';
  const token=jwt.sign({sub:admin.userId,sid,org:admin.organisationId,role:admin.role,cafes:admin.assignedCafeIds,sv:0,usv:0,pv:0,type:'access'},secret,{expiresIn:'1h',issuer:'zamorin-cafe-erp-api',audience:'zamorin-cafe-erp'});
  await Session.deleteOne({sessionId:sid});
  await Session.create({sessionId:sid,organisationId:admin.organisationId,userId:admin.userId,roleSnapshot:admin.role,assignedCafeIdsSnapshot:admin.assignedCafeIds,tokenFamilyId:'FAM3',accessTokenHash:'H',refreshTokenHash:'H',sessionVersion:0,userSessionVersionSnapshot:0,permissionsVersionSnapshot:0,status:'ACTIVE',device:{deviceId:'D3',deviceName:'Test',deviceType:'DESKTOP'},issuedAt:now,lastActivityAt:now,mfaVerified:true,mfaVerifiedAt:now,stepUpVerifiedAt:now,accessTokenExpiresAt:new Date(now.getTime()+3600000),refreshTokenExpiresAt:new Date(now.getTime()+86400000),absoluteExpiresAt:new Date(now.getTime()+86400000),idleTimeoutMinutes:60,createdBy:admin.userId});
  const cookie='zamorin_access_token='+token+'; zamorin_session_id='+sid;
  const origin='http://127.0.0.1:'+PORT;
  const r=await fetch('http://127.0.0.1:'+PORT+'/api/v1/bills',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,Origin:origin},body:JSON.stringify({cafeId:admin.assignedCafeIds[0],orderType:'DINE_IN',tableNumber:'T-SMOKE',lineItems:[{menuItemId:item.menuItemId,quantity:1}],paymentMethod:'CASH',isImmediateCompletion:true})});
  const body=await r.text();
  console.log('POST /bills WITH allowedOrigins fix: '+r.status+' '+(r.status===201?'PASS':'FAIL'));
  console.log('Body prefix: '+body.slice(0,150));
  server.close(); await mongoose.disconnect(); process.exit(r.status===201?0:1);
}
run().catch(e=>{console.error(e.message);process.exit(1);});
