'use strict';
const assert=require('node:assert/strict'),http=require('node:http'),test=require('node:test');
const {createApp}=require('../src/server'),{User}=require('../src/models/User'),{Session}=require('../src/models/Session'),auth=require('../src/services/authService');
const U=()=>new User({userId:'MU-0001',organisationId:'ORG-TEST',name:'Test Master',email:'master@example.test',role:'MASTER',accountStatus:'ACTIVE',assignedCafeIds:[],isPrimaryMaster:false,passwordHash:'x',sessionVersion:0,permissionsVersion:0,mfaEnabled:true,mfaMethod:'TOTP',createdBy:'SYSTEM'});
function S(id='SS-20260808-0100',x={}){const s={sessionId:id,organisationId:'ORG-TEST',userId:'MU-0001',roleSnapshot:'MASTER',sessionVersion:0,userSessionVersionSnapshot:0,permissionsVersionSnapshot:0,status:'ACTIVE',mfaVerified:true,mfaVerifiedAt:new Date(),stepUpVerifiedAt:null,tokenFamilyId:'NOLEAK',device:{deviceId:'NOLEAK',deviceName:'Office Laptop',deviceType:'LAPTOP',operatingSystem:'Windows',browser:'Chrome',userAgent:'NOLEAK',pushSubscriptionId:'NOLEAK'},network:{ipAddressMasked:'203.0.113.xxx',country:'IN',region:'Karnataka',city:'Bengaluru'},issuedAt:new Date(),lastActivityAt:new Date(),accessTokenExpiresAt:new Date(),refreshTokenExpiresAt:new Date(Date.now()+1e6),absoluteExpiresAt:new Date(Date.now()+2e6),idleTimeoutMinutes:30,revokedAt:null,revocationReason:null,createdBy:'SYSTEM',lastCorrelationId:'NOLEAK',isActive(){return this.status==='ACTIVE'},async revoke(o){this.status='REVOKED';this.revokedAt=new Date();this.revokedBy=o.revokedBy;this.revocationReason=o.reason;this.revocationDetails=o.details;return this},...x};return s}
const Q=x=>Object.assign(Promise.resolve(x),{select:async()=>x,lean:async()=>x}),L=x=>({sort:async()=>x,select:async()=>x});
function R(server,path,{method='GET',token}={}){return new Promise((resolve,reject)=>{const u=new URL(path,`http://127.0.0.1:${server.address().port}`),r=http.request({method,hostname:u.hostname,port:u.port,path:u.pathname,headers:{Accept:'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw),headers:res.headers}))});r.on('error',reject);r.end()})}
async function V(t){const a=createApp({allowedOrigins:['*'],production:false}),s=await new Promise(ok=>{const z=a.listen(0,()=>ok(z))});t.after(()=>new Promise(ok=>s.close(ok)));return s}
function A(t,u,s){t.mock.method(auth,'verifyAccessToken',async()=>({payload:{sub:u.userId,org:u.organisationId,role:u.role,sv:0,usv:0,pv:0,sid:s.sessionId,type:'access'},session:s}));t.mock.method(User,'findOne',()=>Q(u))}
test('session routes require auth',async t=>{const s=await V(t),r=await R(s,'/api/v1/auth/sessions');assert.equal(r.status,401);assert.equal(r.body.error?.code,'AUTHENTICATION_REQUIRED')});
test('GET /auth/sessions returns safe DTOs',async t=>{const u=U(),c=S();A(t,u,c);t.mock.method(Session,'findOne',()=>Q(c));t.mock.method(Session,'find',()=>L([c]));const s=await V(t),r=await R(s,'/api/v1/auth/sessions',{token:'x'});assert.equal(r.status,200);assert.equal(r.body.data.currentSessionId,c.sessionId);const x=r.body.data.sessions[0];assert.equal(x.device.deviceName,'Office Laptop');assert.equal(x.network.city,'Bengaluru');for(const k of ['tokenFamilyId','sessionVersion','userSessionVersionSnapshot','permissionsVersionSnapshot','accessTokenExpiresAt','createdBy','lastCorrelationId'])assert.equal(x[k],undefined);for(const k of ['deviceId','userAgent','pushSubscriptionId'])assert.equal(x.device[k],undefined)});
test('logout and logout-all revoke sessions',async t=>{const u=U(),c=S(),o=S('SS-20260808-0101');A(t,u,c);t.mock.method(Session,'findOne',()=>Q(c));t.mock.method(Session,'find',()=>L([c,o]));const s=await V(t);let r=await R(s,'/api/v1/auth/logout',{method:'POST',token:'x'});assert.equal(r.status,200);assert.equal(c.revocationReason,'USER_LOGOUT');c.status='ACTIVE';r=await R(s,'/api/v1/auth/logout-all',{method:'POST',token:'x'});assert.equal(r.status,200);assert.equal(r.body.data.revokedSessionCount,2);assert.equal(c.revocationReason,'LOGOUT_ALL');assert.equal(o.revocationReason,'LOGOUT_ALL')});
test('session revoke is user scoped and missing session is 404',async t=>{const u=U(),c=S(),z=S('SS-20260808-0102'),seen=[];A(t,u,c);t.mock.method(Session,'findOne',f=>{seen.push(f);if(f?.sessionId===z.sessionId&&f?.organisationId===u.organisationId&&f?.userId===u.userId)return Q(z);if(f?.sessionId==='SS-20260808-9999')return Q(null);return Q(c)});const s=await V(t);let r=await R(s,`/api/v1/auth/sessions/${z.sessionId}`,{method:'DELETE',token:'x'});assert.equal(r.status,200);assert.equal(z.status,'REVOKED');assert.ok(seen.some(f=>f?.organisationId===u.organisationId&&f?.userId===u.userId&&f?.sessionId===z.sessionId));r=await R(s,'/api/v1/auth/sessions/SS-20260808-9999',{method:'DELETE',token:'x'});assert.equal(r.status,404);assert.equal(r.body.error?.code,'SESSION_NOT_FOUND')});
