'use strict';
const assert=require('node:assert/strict');
const http=require('node:http');
const test=require('node:test');
const {createApp}=require('../src/server');
const {User}=require('../src/models/User');
const {PasswordResetChallenge}=require('../src/models/PasswordResetChallenge');
const resetService=require('../src/services/passwordResetService');
function request(server,body){return new Promise((resolve,reject)=>{const req=http.request({method:'POST',hostname:'127.0.0.1',port:server.address().port,path:'/api/v1/auth/password/reset/verify',headers:{Accept:'application/json','Content-Type':'application/json'}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw)}));});req.on('error',reject);req.write(JSON.stringify(body));req.end();});}
async function start(t){const app=createApp({allowedOrigins:['*'],production:false});const server=await new Promise(r=>{const x=app.listen(0,()=>r(x));});t.after(()=>new Promise(r=>server.close(r)));return server;}
test('verify reset code gives generic invalid response for unknown account',async t=>{t.mock.method(User,'findOne',()=>null);const server=await start(t);const r=await request(server,{organisationId:'ORG-TEST',email:'missing@example.test',code:'123456'});assert.equal(r.status,400);assert.equal(r.body.error.code,'PASSWORD_RESET_CODE_INVALID');});
test('verify reset code returns token only after successful verification',async t=>{const user={userId:'MU-0001',organisationId:'ORG-TEST',email:'user@example.test',accountStatus:'ACTIVE'};const challenge={challengeId:'PRC-20260809-0001'};t.mock.method(User,'findOne',filter=>{assert.deepEqual(filter,{organisationId:'ORG-TEST',email:'user@example.test'});return user;});t.mock.method(resetService,'isResetEligibleUser',()=>true);t.mock.method(PasswordResetChallenge,'findOne',filter=>{assert.deepEqual(filter,{organisationId:'ORG-TEST',userId:user.userId,status:'PENDING'});return {sort:async()=>challenge};});t.mock.method(resetService,'verifyPasswordResetCode',async input=>{assert.deepEqual(input,{challengeId:challenge.challengeId,code:'654321'});return {challenge,resetToken:'reset-token-secret'};});const server=await start(t);const r=await request(server,{organisationId:'org-test',email:'USER@EXAMPLE.TEST',code:'654321'});assert.equal(r.status,200);assert.equal(r.body.data.challengeId,challenge.challengeId);assert.equal(r.body.data.resetToken,'reset-token-secret');});
