'use strict';

/**
 * ATTENDANCE EXCEPTION — MONGOOSE MODEL (P1: ATTENDANCE INTEGRATION)
 * Generated by: attendanceReconciliationService — NOT fabricated for UI.
 */

const mongoose = require('mongoose');

const EXCEPTION_TYPES = [
  'MISSED_PUNCH',
  'LATE',
  'EARLY_EXIT',
  'UNEXPECTED_ABSENCE',
  'SHIFT_MISMATCH',
  'EXCESSIVE_BREAK',
  'OVERTIME_REVIEW',
  'MISSING_SHIFT',
  'LEAVE_PUNCH_CONFLICT',
  'HOLIDAY_WORK',
];

const EXCEPTION_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH'];

const EXCEPTION_STATUSES = ['OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED'];

const attendanceExceptionSchema = new mongoose.Schema(
  {
    exceptionId: {
      type: String,
      required: true,
      unique: true,
      immutable: true,
      trim: true,
      uppercase: true,
      index: true,
    },

    organisationId: {
      type: String,
      required: true,
      immutable: true,
      trim: true,
      uppercase: true,
      index: true,
    },

    cafeId: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      index: true,
    },

    userId: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
      index: true,
    },

    attendanceId: {
      type: String,
      trim: true,
      uppercase: true,
      default: null,
    },

    businessDate: {
      type: String,
      required: true,
      match: /^\d{4}-\d{2}-\d{2}$/,
      index: true,
    },

    type: {
      type: String,
      required: true,
      enum: EXCEPTION_TYPES,
      index: true,
    },

    severity: {
      type: String,
      enum: EXCEPTION_SEVERITIES,
      default: 'MEDIUM',
    },

    status: {
      type: String,
      enum: EXCEPTION_STATUSES,
      default: 'OPEN',
      index: true,
    },

    description: {
      type: String,
      trim: true,
      maxlength: 500,
      default: '',
    },

    resolvedAt: {
      type: Date,
      default: null,
    },

    resolvedByUserId: {
      type: String,
      trim: true,
      uppercase: true,
      default: null,
    },

    resolutionReason: {
      type: String,
      trim: true,
      maxlength: 1000,
      default: '',
    },

    generatedByService: {
      type: String,
      trim: true,
      default: 'attendanceReconciliationService',
    },
  },
  {
    timestamps: true,
    versionKey: 'version',
    collection: 'attendance_exceptions',
  }
);

attendanceExceptionSchema.index(
  { organisationId: 1, cafeId: 1, businessDate: 1, status: 1 },
  { name: 'org_cafe_date_status' }
);

attendanceExceptionSchema.index(
  { organisationId: 1, userId: 1, businessDate: 1, type: 1 },
  { unique: true, name: 'user_date_type_unique' }
);

const AttendanceException =
  mongoose.models.AttendanceException ||
  mongoose.model('AttendanceException', attendanceExceptionSchema);

module.exports = {
  AttendanceException,
  EXCEPTION_TYPES,
  EXCEPTION_SEVERITIES,
  EXCEPTION_STATUSES,
};
