'use strict';

/**
 * GOVERNED METRICS & SEMANTIC LAYER — SCR-022
 * Defines trusted business metric formulas, source domains, inclusion/exclusion rules,
 * versioning, stewards, and trust classifications for Zamorin Cafe ERP.
 */

const METRICS_DICTIONARY = [
  {
    metricId: 'NET_SALES',
    name: 'Net Sales',
    category: 'Sales',
    businessDefinition: 'Total gross sales revenue minus customer discounts, promotional allowances, and tax, plus inclusive pricing adjustments.',
    formula: 'SUM(GrossSales) - SUM(Discounts) - SUM(Refunds) - SUM(Taxes)',
    sourceDomain: 'POS & Billing',
    sourceFields: ['Bill.items.totalAmount', 'Bill.discountAmount', 'Bill.refundAmount', 'Bill.taxDetails'],
    includedStates: ['PAID', 'SETTLED', 'COMPLETED'],
    excludedStates: ['VOID', 'CANCELLED', 'DRAFT'],
    unit: 'INR',
    timeBasis: 'Business Date (Asia/Kolkata)',
    owner: 'Finance & Accounts',
    version: 'v2.1',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-15',
  },
  {
    metricId: 'GROSS_SALES',
    name: 'Gross Sales',
    category: 'Sales',
    businessDefinition: 'Total face-value bill amount of all completed menu items and retail merchandise before deductions.',
    formula: 'SUM(Bill.items.quantity * Bill.items.unitPrice)',
    sourceDomain: 'POS & Billing',
    sourceFields: ['Bill.items.unitPrice', 'Bill.items.quantity'],
    includedStates: ['PAID', 'SETTLED', 'COMPLETED'],
    excludedStates: ['VOID', 'CANCELLED'],
    unit: 'INR',
    timeBasis: 'Business Date (Asia/Kolkata)',
    owner: 'Commercial & Sales',
    version: 'v1.4',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-15',
  },
  {
    metricId: 'ORDER_COUNT',
    name: 'Total Order Count',
    category: 'Sales',
    businessDefinition: 'Number of unique non-voided sales tickets processed through the POS terminals.',
    formula: 'COUNT(DISTINCT Bill.billId)',
    sourceDomain: 'POS & Billing',
    sourceFields: ['Bill.billId'],
    includedStates: ['PAID', 'SETTLED', 'COMPLETED'],
    excludedStates: ['VOID', 'CANCELLED'],
    unit: 'COUNT',
    timeBasis: 'Business Date (Asia/Kolkata)',
    owner: 'POS Operations',
    version: 'v1.2',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-10',
  },
  {
    metricId: 'AOV',
    name: 'Average Order Value (AOV)',
    category: 'Sales',
    businessDefinition: 'Mean net sales revenue generated per completed customer transaction ticket.',
    formula: 'NetSales / OrderCount',
    sourceDomain: 'POS & Billing',
    sourceFields: ['NetSales', 'OrderCount'],
    includedStates: ['PAID', 'SETTLED'],
    excludedStates: ['VOID', 'CANCELLED'],
    unit: 'INR',
    timeBasis: 'Business Date (Asia/Kolkata)',
    owner: 'Commercial & Sales',
    version: 'v1.3',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-10',
  },
  {
    metricId: 'GROSS_MARGIN_PCT',
    name: 'Gross Margin %',
    category: 'Finance',
    businessDefinition: 'Percentage of net revenue retained after deducting raw material recipe cost of goods sold (COGS).',
    formula: '((NetSales - COGS) / NetSales) * 100',
    sourceDomain: 'Finance & Menu',
    sourceFields: ['NetSales', 'Recipe.totalCostPaise'],
    includedStates: ['POSTED', 'SETTLED'],
    excludedStates: ['DRAFT', 'VOID'],
    unit: 'PERCENT',
    timeBasis: 'Fiscal Month',
    owner: 'Finance & Accounts',
    version: 'v2.0',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-12',
  },
  {
    metricId: 'LABOUR_COST_PCT',
    name: 'Labour Cost % of Sales',
    category: 'Workforce',
    businessDefinition: 'Total gross employee remuneration and statutory employer contributions expressed as a ratio of Net Sales.',
    formula: '(GrossPayroll / NetSales) * 100',
    sourceDomain: 'Payroll & Finance',
    sourceFields: ['PayrollRun.grossPayPaise', 'NetSales'],
    includedStates: ['DISBURSED', 'APPROVED'],
    excludedStates: ['DRAFT', 'VOID'],
    unit: 'PERCENT',
    timeBasis: 'Pay Period / Month',
    owner: 'People & Workforce',
    version: 'v1.8',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-14',
  },
  {
    metricId: 'INVENTORY_VALUATION',
    name: 'Total Inventory Valuation',
    category: 'Inventory',
    businessDefinition: 'Current monetary value of on-hand raw material, packaging, and retail stock evaluated under weighted-average cost.',
    formula: 'SUM(InventoryLot.quantityOnHand * InventoryLot.unitCostPaise)',
    sourceDomain: 'Inventory & Stock',
    sourceFields: ['InventoryLot.quantityOnHand', 'InventoryLot.unitCostPaise'],
    includedStates: ['AVAILABLE', 'ON_HOLD'],
    excludedStates: ['DISPOSED', 'CONSUMED', 'WRITTEN_OFF'],
    unit: 'INR',
    timeBasis: 'As-of Snapshot',
    owner: 'Supply Chain & Inventory',
    version: 'v2.2',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-18',
  },
  {
    metricId: 'WASTE_VALUATION',
    name: 'Wastage & Spoilage Valuation',
    category: 'Inventory',
    businessDefinition: 'Total monetary loss from discarded, expired, or damaged raw materials and prepared food items.',
    formula: 'SUM(WastageRecord.quantity * WastageRecord.unitCostPaise)',
    sourceDomain: 'Inventory & Stock',
    sourceFields: ['WastageRecord.quantity', 'WastageRecord.unitCostPaise'],
    includedStates: ['APPROVED', 'LOGGED'],
    excludedStates: ['REJECTED', 'DRAFT'],
    unit: 'INR',
    timeBasis: 'Business Date / Period',
    owner: 'Supply Chain & Inventory',
    version: 'v1.5',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-18',
  },
  {
    metricId: 'PROCUREMENT_COMMITMENTS',
    name: 'Open Procurement Commitments',
    category: 'Procurement',
    businessDefinition: 'Total monetary commitment of purchase orders approved and dispatched to vendors awaiting GRN receiving.',
    formula: 'SUM(PurchaseOrder.totalPaisa WHERE status IN ["APPROVED", "ORDERED", "PARTIALLY_RECEIVED"])',
    sourceDomain: 'Procurement',
    sourceFields: ['PurchaseOrder.totalPaisa', 'PurchaseOrder.status'],
    includedStates: ['APPROVED', 'ORDERED', 'PARTIALLY_RECEIVED'],
    excludedStates: ['DRAFT', 'CLOSED', 'CANCELLED'],
    unit: 'INR',
    timeBasis: 'As-of Current',
    owner: 'Procurement & Sourcing',
    version: 'v1.6',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-19',
  },
  {
    metricId: 'OPEN_NCRS',
    name: 'Open Non-Conformances',
    category: 'Quality',
    businessDefinition: 'Count of active food safety, vendor defect, and operational quality investigations under containment.',
    formula: 'COUNT(NCR.ncrId WHERE status IN ["OPEN", "CONTAINED", "UNDER_INVESTIGATION"])',
    sourceDomain: 'Quality & Compliance',
    sourceFields: ['NCR.ncrId', 'NCR.status'],
    includedStates: ['OPEN', 'CONTAINED', 'UNDER_INVESTIGATION'],
    excludedStates: ['CLOSED'],
    unit: 'COUNT',
    timeBasis: 'Real-time',
    owner: 'Quality & Food Safety',
    version: 'v1.4',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-20',
  },
  {
    metricId: 'ASSET_DOWNTIME_HOURS',
    name: 'Asset Breakdown Downtime',
    category: 'Assets',
    businessDefinition: 'Cumulative equipment breakdown hours on critical espresso machines, grinders, and refrigeration units.',
    formula: 'SUM(WorkOrder.downtimeMinutes) / 60',
    sourceDomain: 'Assets & Maintenance',
    sourceFields: ['WorkOrder.downtimeMinutes'],
    includedStates: ['RESOLVED', 'IN_PROGRESS'],
    excludedStates: ['CANCELLED'],
    unit: 'HOURS',
    timeBasis: 'Period Total',
    owner: 'Facilities & Assets',
    version: 'v1.1',
    trustStatus: 'GOVERNED',
    lastReviewed: '2026-08-10',
  },
  {
    metricId: 'SAME_STORE_SALES_GROWTH',
    name: 'Same-Store / Like-for-Like Sales Growth %',
    category: 'Portfolio',
    businessDefinition: 'Year-over-year revenue comparison including only mature café locations operating for at least 12 full calendar months.',
    formula: '((MatureCafeNetSales_Current - MatureCafeNetSales_Prior) / MatureCafeNetSales_Prior) * 100',
    sourceDomain: 'Portfolio Analytics',
    sourceFields: ['NetSales', 'Cafe.openedAt'],
    includedStates: ['MATURE_CAFES_ONLY'],
    excludedStates: ['NEW_CAFES_RAMPING', 'CLOSED_TEMPORARILY'],
    unit: 'PERCENT',
    timeBasis: 'Year-over-Year',
    owner: 'Executive Management',
    version: 'v2.0',
    trustStatus: 'CERTIFIED',
    lastReviewed: '2026-08-15',
  },
];

class MetricsService {
  /**
   * Retrieves the full governed metric dictionary.
   */
  static getDictionary() {
    return METRICS_DICTIONARY;
  }

  /**
   * Retrieves metadata for a specific metric.
   */
  static getMetricById(metricId) {
    return METRICS_DICTIONARY.find((m) => m.metricId === metricId) || null;
  }
}

module.exports = {
  MetricsService,
  METRICS_DICTIONARY,
};
