'use strict';

/**
 * ZAMORIN CAFÉ ERP — REPORTING FOUNDATION
 * Module: metricRegistry.js
 * 
 * Central Canonical Metric Registry:
 * - Single source of truth for every Zamorin analytical metric.
 * - Enforces stable metric IDs, semantic versions, domain ownership, and classifications.
 * - Transparently tracks metric actuality and calculation availability.
 * - Zero fabricated formulas or synthetic calculations.
 */

const CANONICAL_METRICS = {
  // ─── 1. SALES DOMAIN ────────────────────────────────────────────────────────
  GROSS_SALES: {
    metricId: 'GROSS_SALES',
    displayName: 'Gross Sales Revenue (Pre-Tax)',
    description: 'Total pre-tax face-value sales amount of all menu items and retail merchandise before customer discounts, returns/refunds, and taxes. Preserves original pre-refund transaction activity.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.subtotalPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.3.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL', // Operational calculation from transactional bills; not yet reconciled against GL postings
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'HOUR', 'DAY_OF_WEEK', 'DAYPART', 'CAFE', 'SERVICE_MODE', 'ORDER_SOURCE', 'PAYMENT_METHOD'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    versionCompatibility: 'Preferred Evidence Hierarchy: A) Current Bill: If subtotalPaisa exists and is authoritative -> subtotalPaisa. B) Legacy Bill with authoritative line-level pre-discount subtotals -> SUM(Bill.lineItems[i].lineSubtotalPaisa). C) Legacy Bill with taxable amount AND stored discount -> taxableAmountPaisa + discountPaisa. D) Legacy Bill with total + tax + discount -> totalPaisa - taxPaisa + discountPaisa. E) Insufficient legacy data -> null, Data Quality = PARTIAL, Warning = LEGACY_BILL_INSUFFICIENT_GROSS_SALES_FIELDS. Reverse tax multiplier estimation or flat tax fallback is strictly prohibited.',
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  SALES_BEFORE_TAX: {
    metricId: 'SALES_BEFORE_TAX',
    displayName: 'Sales Before Tax (Pre-Tax Net of Discounts)',
    description: 'Pre-tax commercial revenue recognized after customer promotional and loyalty discounts, but before applicable return/refund deductions.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.subtotalPaisa - Bill.discountPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.2.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'HOUR', 'DAY_OF_WEEK', 'DAYPART', 'CAFE', 'SERVICE_MODE', 'ORDER_SOURCE', 'PAYMENT_METHOD'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: ['GROSS_SALES', 'DISCOUNT_AMOUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  NET_SALES: {
    metricId: 'NET_SALES',
    displayName: 'Net Sales Revenue',
    description: 'Canonical net revenue recognized: Pre-tax Gross Sales (subtotalPaisa) minus discounts minus pre-tax refunds on completed, partially refunded, and refunded bills. Does not include collected GST. Zero-refund bills resolve with 100% precision. Full refunds zeroize recognized revenue (Net Sales = 0). Where partial refunds lack stored line-item tax component allocation, partial-refund adjustments are marked PARTIAL_SOURCE rather than using estimated tax multipliers.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: '(Bill.subtotalPaisa - Bill.discountPaisa) - PreTaxRefunds',
    sourceModels: ['Bill'],
    formulaVersion: '1.3.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL', // Operational calculation from transactional bills; not yet reconciled against GL postings
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'HOUR', 'DAY_OF_WEEK', 'DAYPART', 'CAFE', 'SERVICE_MODE', 'ORDER_SOURCE', 'PAYMENT_METHOD'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: ['GROSS_SALES', 'DISCOUNT_AMOUNT', 'REFUND_AMOUNT'],
    versionCompatibility: 'Zero-refund bills resolve with 100% precision. Fully refunded bills produce exact 0 net sales. Partial refunds without authoritative CreditNote pre-tax breakdown are flagged as PARTIAL_SOURCE; gross-to-net bridge enforces NET_SALES <= GROSS_SALES.',
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  CUSTOMER_RECEIPT_TOTAL: {
    metricId: 'CUSTOMER_RECEIPT_TOTAL',
    displayName: 'Customer Receipt Total (Tax-Inclusive Collections)',
    description: 'Total gross cash and electronic tender payable billed to customers inclusive of GST and post-discount.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.totalPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.1.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'HOUR', 'DAY_OF_WEEK', 'DAYPART', 'CAFE', 'SERVICE_MODE', 'ORDER_SOURCE', 'PAYMENT_METHOD'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  NET_CUSTOMER_RECEIPTS: {
    metricId: 'NET_CUSTOMER_RECEIPTS',
    displayName: 'Net Customer Receipts',
    description: 'Net customer tender receipts after deducting customer refunds returned.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.totalPaisa - Bill.refundedTotalPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.1.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'HOUR', 'DAY_OF_WEEK', 'DAYPART', 'CAFE', 'SERVICE_MODE', 'ORDER_SOURCE', 'PAYMENT_METHOD'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: ['CUSTOMER_RECEIPT_TOTAL', 'REFUND_AMOUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  ORDER_COUNT: {
    metricId: 'ORDER_COUNT',
    displayName: 'Completed Order Count',
    description: 'Count of unique non-voided completed transactions processed by point of sale.',
    domain: 'SALES',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'Bill.billId',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'HOUR', 'DAY_OF_WEEK', 'DAYPART', 'CAFE', 'SERVICE_MODE', 'ORDER_SOURCE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  AVERAGE_ORDER_VALUE: {
    metricId: 'AVERAGE_ORDER_VALUE',
    displayName: 'Average Order Value (AOV)',
    description: 'Mean net sales revenue generated per completed customer transaction ticket.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES / ORDER_COUNT',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'DAYPART', 'CAFE', 'SERVICE_MODE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: ['NET_SALES', 'ORDER_COUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  DISCOUNT_AMOUNT: {
    metricId: 'DISCOUNT_AMOUNT',
    displayName: 'Discount & Allowances',
    description: 'Total value of customer promotional, coupon, and loyalty discounts deducted from bills.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.discountPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'SERVICE_MODE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  DISCOUNT_RATE: {
    metricId: 'DISCOUNT_RATE',
    displayName: 'Discount Rate %',
    description: 'Percentage of gross sales conceded in discounts and promotional allowances.',
    domain: 'SALES',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(DISCOUNT_AMOUNT / GROSS_SALES) * 100',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: ['DISCOUNT_AMOUNT', 'GROSS_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  TAX_CHARGED: {
    metricId: 'TAX_CHARGED',
    displayName: 'Tax Charged (Gross GST)',
    description: 'Cumulative Goods and Services Tax (CGST + SGST + IGST) charged on completed and qualifying bills. Represents gross statutory tax before refund adjustments.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.taxPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  TAX_AMOUNT: {
    metricId: 'TAX_AMOUNT',
    displayName: 'Tax Collected (Gross GST)',
    description: 'Cumulative Goods and Services Tax (CGST + SGST + IGST) collected on eligible bills. Represents gross statutory tax before refunds.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.taxPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.1.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  NET_TAX: {
    metricId: 'NET_TAX',
    displayName: 'Net Statutory Tax (GST After Refunds)',
    description: 'Net statutory Goods and Services Tax liability after deducting GST refunded to customers. For zero-refund periods or periods with full refunds, exact net tax is calculated. For periods with partial refunds lacking pre-tax/tax allocations, marked PARTIAL_SOURCE.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'TAX_CHARGED - REFUNDED_TAX',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'DERIVED',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: ['TAX_CHARGED', 'REFUNDED_TAX'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  CUSTOMER_REFUND_TOTAL: {
    metricId: 'CUSTOMER_REFUND_TOTAL',
    displayName: 'Customer Refund Total (Gross Tender Returned)',
    description: 'Total cash and electronic tender refunded to customers inclusive of tax and post-discount adjustments.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.refundedTotalPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  PRE_TAX_REFUND: {
    metricId: 'PRE_TAX_REFUND',
    displayName: 'Pre-Tax Sales Returns & Refunds',
    description: 'Pre-tax sales return deduction credited back to customers. In partial refunds lacking credit note tax allocation, marked PARTIAL_SOURCE.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'CreditNote.taxableAdjustmentPaisa || FullRefundPreTax',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  REFUNDED_TAX: {
    metricId: 'REFUNDED_TAX',
    displayName: 'Refunded GST (Statutory Tax Returned)',
    description: 'Statutory Goods and Services Tax returned to customers on refunds and credit notes. In partial refunds without stored line tax allocation, marked PARTIAL_SOURCE.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'CreditNote.taxAdjustmentPaisa || FullRefundTax',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  REFUND_AMOUNT: {
    metricId: 'REFUND_AMOUNT',
    displayName: 'Refunds & Returns',
    description: 'Total value of refunds credited back to customers for returned or disputed orders.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.refundedTotalPaisa',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  VOID_AMOUNT: {
    metricId: 'VOID_AMOUNT',
    displayName: 'Voided Invoices Value',
    description: 'Total value of cancelled or voided orders after terminal registration.',
    domain: 'SALES',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Bill.totalPaisa WHERE status == "VOIDED"',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['VOIDED'],
    excludedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED', 'REFUNDED', 'OPEN'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  SALES_GROWTH: {
    metricId: 'SALES_GROWTH',
    displayName: 'Sales Growth %',
    description: 'Percentage variation in Net Sales between current period and comparison period.',
    domain: 'SALES',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '((NET_SALES_CURRENT - NET_SALES_PRIOR) / NET_SALES_PRIOR) * 100',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'EXECUTIVE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['OPEN', 'VOIDED', 'PAYMENT_REVERSED', 'REFUNDED'],
    dependencies: ['NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  // ─── 2. PROFITABILITY & P&L DOMAIN ──────────────────────────────────────────
  GROSS_PROFIT: {
    metricId: 'GROSS_PROFIT',
    displayName: 'Gross Operating Profit',
    description: 'Net Sales Revenue minus Cost of Goods Sold (COGS). UNAVAILABLE because canonical COGS is not posted.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES - COGS',
    sourceModels: ['Bill', 'InventoryLot', 'MenuItem'],
    formulaVersion: '1.1.0',
    calculationType: 'DERIVED',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['POSTED', 'SETTLED'],
    excludedStatuses: ['DRAFT', 'VOID'],
    dependencies: ['NET_SALES', 'COGS'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  GROSS_MARGIN_PERCENT: {
    metricId: 'GROSS_MARGIN_PERCENT',
    displayName: 'Gross Margin %',
    description: 'Gross Profit expressed as a percentage of Net Sales Revenue. UNAVAILABLE because Gross Profit is unavailable.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(GROSS_PROFIT / NET_SALES) * 100',
    sourceModels: ['Bill', 'InventoryLot', 'MenuItem'],
    formulaVersion: '1.1.0',
    calculationType: 'PERCENTAGE',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['POSTED'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['GROSS_PROFIT', 'NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  COGS: {
    metricId: 'COGS',
    displayName: 'Cost of Goods Sold (COGS)',
    description: 'Direct raw material and packaging expenditure consumed in fulfilling menu items sold.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Automated double-entry COGS posting from inventory consumption',
    sourceModels: ['InventoryLot', 'StockMovement', 'MenuItem'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY', 'MENU_ITEM'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['POSTED'],
    excludedStatuses: ['DRAFT'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  COGS_PERCENT: {
    metricId: 'COGS_PERCENT',
    displayName: 'COGS % of Sales',
    description: 'Ratio of raw material cost to net sales revenue. UNAVAILABLE because COGS is unavailable.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(COGS / NET_SALES) * 100',
    sourceModels: ['InventoryLot', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['POSTED'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['COGS', 'NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  GROSS_PAYROLL: {
    metricId: 'GROSS_PAYROLL',
    displayName: 'Gross Employee Payroll',
    description: 'Gross employee remuneration before deductions. Does not include employer statutory contributions (EPF/ESI) or employer overheads.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'PayrollRun.totalGrossPaise',
    sourceModels: ['PayrollRun'],
    formulaVersion: '1.1.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['APPROVED', 'PAID', 'ISSUED'],
    excludedStatuses: ['DRAFT', 'REJECTED', 'CANCELLED'],
    dependencies: [],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LABOUR_COST: {
    metricId: 'LABOUR_COST',
    displayName: 'Labour Cost (Operational Gross Payroll)',
    description: 'Gross employee payroll disbursements. Incomplete as full economic labour cost because employer statutory contributions (employer EPF, employer ESI, gratuity provision, employer insurance) are not tracked in current canonical source models. True economic labour cost requires statutory employer overheads.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'PayrollRun.totalGrossPaise || Payslip.grossEarningsPaise',
    sourceModels: ['PayrollRun', 'Payslip'],
    formulaVersion: '1.2.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['APPROVED', 'PAID', 'ISSUED'],
    excludedStatuses: ['DRAFT', 'REJECTED', 'CANCELLED'],
    dependencies: ['GROSS_PAYROLL'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
    missingComponents: ['EMPLOYER_EPF', 'EMPLOYER_ESI', 'GRATUITY_PROVISION', 'EMPLOYER_INSURANCE'],
  },

  GROSS_PAYROLL_PERCENT: {
    metricId: 'GROSS_PAYROLL_PERCENT',
    displayName: 'Gross Payroll % of Sales',
    description: 'Ratio of gross employee payroll disbursements (remuneration before statutory employer contributions) to Net Sales Revenue.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(GROSS_PAYROLL / NET_SALES) * 100',
    sourceModels: ['PayrollRun', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'PAID'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['GROSS_PAYROLL', 'NET_SALES'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LABOUR_PERCENT: {
    metricId: 'LABOUR_PERCENT',
    displayName: 'Labour % of Sales (Operational Basis)',
    description: 'Ratio of recorded employee payroll disbursements to Net Sales Revenue. Marked PARTIAL_SOURCE as underlying labour cost reflects employee gross pay and omits employer statutory overheads.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(LABOUR_COST / NET_SALES) * 100',
    sourceModels: ['PayrollRun', 'Bill'],
    formulaVersion: '1.1.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'PAID'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['LABOUR_COST', 'NET_SALES'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  PRIME_COST: {
    metricId: 'PRIME_COST',
    displayName: 'Actual Prime Cost (COGS + Labour)',
    description: 'Cumulative total of raw material cost of goods sold plus labour expenditure. UNAVAILABLE because actual posted inventory COGS is unavailable.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'COGS + LABOUR_COST',
    sourceModels: ['InventoryLot', 'PayrollRun'],
    formulaVersion: '1.1.0',
    calculationType: 'DERIVED',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'POSTED'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['COGS', 'LABOUR_COST'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  THEORETICAL_COGS: {
    metricId: 'THEORETICAL_COGS',
    displayName: 'Theoretical COGS (Recipe BOM Consumption)',
    description: 'Theoretical raw material consumption cost derived by exploding menu item recipe Bill of Materials against sales mix. Marked as ESTIMATED.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Recipe BOM Exploded Paired With Bill Line Items',
    sourceModels: ['MenuItem', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'DERIVED',
    actuality: 'ESTIMATED',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY', 'MENU_ITEM'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED', 'CANCELLED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  THEORETICAL_PRIME_COST: {
    metricId: 'THEORETICAL_PRIME_COST',
    displayName: 'Theoretical Prime Cost (Recipe BOM + Gross Payroll)',
    description: 'Engineered estimate: Theoretical recipe raw material consumption plus gross employee payroll disbursements. Excludes employer statutory overheads (EPF/ESI/gratuity) and physical stock shrinkage/waste.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'THEORETICAL_COGS + GROSS_PAYROLL',
    sourceModels: ['InventoryLot', 'Bill', 'PayrollRun'],
    formulaVersion: '1.2.0',
    calculationType: 'DERIVED',
    actuality: 'ESTIMATED',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'POSTED'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['THEORETICAL_COGS', 'GROSS_PAYROLL'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  ESTIMATED_CONTRIBUTION: {
    metricId: 'ESTIMATED_CONTRIBUTION',
    displayName: 'Estimated Contribution (Net Sales - Theoretical COGS)',
    description: 'Item or category net sales revenue minus theoretical recipe BOM ingredient cost. Visibly marked as ESTIMATED.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES - THEORETICAL_COGS',
    sourceModels: ['Bill', 'MenuItem', 'Recipe', 'GlobalInventoryItem'],
    formulaVersion: '1.0.0',
    calculationType: 'DERIVED',
    actuality: 'ESTIMATED',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY', 'MENU_ITEM'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED', 'CANCELLED'],
    dependencies: ['NET_SALES', 'THEORETICAL_COGS'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  ESTIMATED_CONTRIBUTION_PERCENT: {
    metricId: 'ESTIMATED_CONTRIBUTION_PERCENT',
    displayName: 'Estimated Contribution %',
    description: 'Estimated contribution expressed as a percentage of Net Item Sales. Safe against zero net sales.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(ESTIMATED_CONTRIBUTION / NET_SALES) * 100',
    sourceModels: ['Bill', 'MenuItem', 'Recipe', 'GlobalInventoryItem'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ESTIMATED',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY', 'MENU_ITEM'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED', 'CANCELLED'],
    dependencies: ['ESTIMATED_CONTRIBUTION', 'NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  MODIFIER_ATTACH_RATE: {
    metricId: 'MODIFIER_ATTACH_RATE',
    displayName: 'Modifier Attach Rate %',
    description: 'Ratio of base item units or bills ordered with a modifier to eligible base item units sold.',
    domain: 'SALES',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(Units With Modifier / Eligible Base Item Units) * 100',
    sourceModels: ['Bill', 'MenuItem', 'ModifierGroup'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY', 'MENU_ITEM', 'MODIFIER'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED', 'CANCELLED'],
    dependencies: ['ORDER_COUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'AVAILABLE',
  },

  BILL_PENETRATION: {
    metricId: 'BILL_PENETRATION',
    displayName: 'Bill Penetration %',
    description: 'Percentage of total finalized bills containing at least one unit of this item or category.',
    domain: 'SALES',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(Bills Containing Item / Total Bills) * 100',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY', 'MENU_ITEM'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED', 'CANCELLED'],
    dependencies: ['ORDER_COUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'AVAILABLE',
  },

  PRIME_COST_PERCENT: {
    metricId: 'PRIME_COST_PERCENT',
    displayName: 'Prime Cost %',
    description: 'Prime Cost expressed as a ratio of Net Sales Revenue. UNAVAILABLE because actual Prime Cost is unavailable.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(PRIME_COST / NET_SALES) * 100',
    sourceModels: ['InventoryLot', 'PayrollRun', 'Bill'],
    formulaVersion: '1.1.0',
    calculationType: 'PERCENTAGE',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'POSTED'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['PRIME_COST', 'NET_SALES'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  OPERATING_EXPENSE: {
    metricId: 'OPERATING_EXPENSE',
    displayName: 'Store Operating Expenses (Opex)',
    description: 'Cumulative store operating costs (rent, utilities, maintenance, packaging, administrative overheads). Excludes inventory purchases and payroll disbursements to prevent double-counting.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'Expense.amountPaisa WHERE category NOT IN ["INVENTORY", "PAYROLL", "CAPEX", "TAX"]',
    sourceModels: ['Expense'],
    formulaVersion: '1.1.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'EXPENSE_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['APPROVED', 'PAID'],
    excludedStatuses: ['DRAFT', 'SUBMITTED', 'REJECTED', 'CANCELLED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  EBITDA: {
    metricId: 'EBITDA',
    displayName: 'Store Operating EBITDA',
    description: 'Store operating EBITDA (Net Sales minus COGS, Labour, and Operating Expenses). Currently UNAVAILABLE because canonical COGS is not posted.',
    domain: 'PROFITABILITY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES - (COGS + LABOUR_COST + OPERATING_EXPENSE)',
    sourceModels: ['Bill', 'Expense', 'PayrollRun'],
    formulaVersion: '1.1.0',
    calculationType: 'DERIVED',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: ['APPROVED', 'PAID', 'COMPLETED'],
    excludedStatuses: ['DRAFT', 'CANCELLED'],
    dependencies: ['NET_SALES', 'COGS', 'LABOUR_COST', 'OPERATING_EXPENSE'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  EBITDA_MARGIN: {
    metricId: 'EBITDA_MARGIN',
    displayName: 'EBITDA Margin %',
    description: 'Store operating EBITDA expressed as a percentage of Net Sales Revenue. Currently UNAVAILABLE because EBITDA is unavailable.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(EBITDA / NET_SALES) * 100',
    sourceModels: ['Bill', 'Expense', 'PayrollRun'],
    formulaVersion: '1.1.0',
    calculationType: 'PERCENTAGE',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'PAID', 'COMPLETED'],
    excludedStatuses: ['DRAFT', 'CANCELLED'],
    dependencies: ['EBITDA', 'NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  // ─── 3. INVENTORY DOMAIN ───────────────────────────────────────────────────
  INVENTORY_VALUE: {
    metricId: 'INVENTORY_VALUE',
    displayName: 'Total Inventory Valuation',
    description: 'Monetary value of on-hand raw material, packaging, and retail stock evaluated under weighted-average cost.',
    domain: 'INVENTORY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'SUM(InventoryLot.quantityOnHand * InventoryLot.unitCostPaise)',
    sourceModels: ['InventoryLot'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'SUPPLY_CHAIN',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'INVENTORY_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['AVAILABLE', 'ON_HOLD'],
    excludedStatuses: ['DISPOSED', 'CONSUMED', 'WRITTEN_OFF'],
    dependencies: [],
    timeBasis: 'SNAPSHOT',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  INVENTORY_USAGE: {
    metricId: 'INVENTORY_USAGE',
    displayName: 'Inventory Recipe Usage',
    description: 'Theoretical volume and value of raw materials consumed according to standard recipe BOM multipliers.',
    domain: 'INVENTORY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'SUM(BillItem.quantity * Recipe.ingredientCostPaise)',
    sourceModels: ['Bill', 'Recipe'],
    formulaVersion: '1.0.0',
    calculationType: 'DERIVED',
    actuality: 'ESTIMATED',
    ownerDomain: 'SUPPLY_CHAIN',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'MENU_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  WASTE_VALUE: {
    metricId: 'WASTE_VALUE',
    displayName: 'Wastage & Spoilage Valuation',
    description: 'Total monetary loss from discarded, expired, or damaged raw materials and prepared food items.',
    domain: 'INVENTORY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'SUM(WastageRecord.quantity * WastageRecord.unitCostPaise)',
    sourceModels: ['WastageRecord'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'SUPPLY_CHAIN',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'INVENTORY_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'LOGGED'],
    excludedStatuses: ['REJECTED', 'DRAFT'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  WASTE_PERCENT: {
    metricId: 'WASTE_PERCENT',
    displayName: 'Wastage % of Gross Sales',
    description: 'Total wastage valuation expressed as a ratio of Gross Sales Revenue.',
    domain: 'INVENTORY',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(WASTE_VALUE / GROSS_SALES) * 100',
    sourceModels: ['WastageRecord', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'SUPPLY_CHAIN',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['APPROVED'],
    excludedStatuses: ['DRAFT'],
    dependencies: ['WASTE_VALUE', 'GROSS_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  STOCK_VARIANCE: {
    metricId: 'STOCK_VARIANCE',
    displayName: 'Stock Cycle Count Variance',
    description: 'Discrepancy between system ledger on-hand stock and physical count audit.',
    domain: 'INVENTORY',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'SUM(InventoryCycleCount.varianceQuantity * InventoryCycleCount.unitCostPaise)',
    sourceModels: ['InventoryCycleCount'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'SUPPLY_CHAIN',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'INVENTORY_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['FINALIZED', 'AUDITED'],
    excludedStatuses: ['IN_PROGRESS', 'DRAFT'],
    dependencies: [],
    timeBasis: 'SNAPSHOT',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  INVENTORY_DAYS_COVER: {
    metricId: 'INVENTORY_DAYS_COVER',
    displayName: 'Inventory Days of Cover',
    description: 'Estimated days of supply remaining based on current stock valuation and 30-day average daily usage. UNAVAILABLE because COGS is unavailable.',
    domain: 'INVENTORY',
    unit: 'DAYS',
    format: 'DECIMAL_2DP',
    source: 'INVENTORY_VALUE / (AverageDailyCOGS)',
    sourceModels: ['InventoryLot', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'SUPPLY_CHAIN',
    classification: 'INTERNAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['AVAILABLE'],
    excludedStatuses: ['DISPOSED'],
    dependencies: ['INVENTORY_VALUE', 'COGS'],
    timeBasis: 'SNAPSHOT',
    nullPolicy: 'NULL_IF_UNAVAILABLE',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  // ─── 4. WORKFORCE DOMAIN ───────────────────────────────────────────────────
  LABOUR_HOURS: {
    metricId: 'LABOUR_HOURS',
    displayName: 'Productive Labour Hours',
    description: 'Cumulative regular and overtime hours logged and approved via biometric/presence attendance submissions.',
    domain: 'WORKFORCE',
    unit: 'HOURS',
    format: 'DURATION_HOURS',
    source: 'SUM(AttendanceSubmission.workMinutes) / 60',
    sourceModels: ['AttendanceSubmission'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE', 'SHIFT'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['VERIFIED', 'APPROVED'],
    excludedStatuses: ['REJECTED', 'PENDING'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  SALES_PER_LABOUR_HOUR: {
    metricId: 'SALES_PER_LABOUR_HOUR',
    displayName: 'Sales per Labour Hour (SPLH)',
    description: 'Productivity ratio: Net Sales Revenue generated per productive employee labour hour worked.',
    domain: 'WORKFORCE',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES / LABOUR_HOURS',
    sourceModels: ['Bill', 'AttendanceSubmission'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'DAYPART'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'APPROVED'],
    excludedStatuses: ['DRAFT', 'REJECTED'],
    dependencies: ['NET_SALES', 'LABOUR_HOURS'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  ATTENDANCE_RATE: {
    metricId: 'ATTENDANCE_RATE',
    displayName: 'Staff Attendance Adherence Rate %',
    description: 'Ratio of scheduled shift roster slots fulfilled with verified attendance punches.',
    domain: 'WORKFORCE',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(FulfilledShifts / ScheduledShifts) * 100',
    sourceModels: ['ShiftRoster', 'AttendanceSubmission'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'VERIFIED'],
    excludedStatuses: ['CANCELLED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  OVERTIME_HOURS: {
    metricId: 'OVERTIME_HOURS',
    displayName: 'Approved Overtime Hours',
    description: 'Total approved labour hours worked beyond standard scheduled roster boundaries.',
    domain: 'WORKFORCE',
    unit: 'HOURS',
    format: 'DURATION_HOURS',
    source: 'SUM(AttendanceSubmission.overtimeMinutes) / 60',
    sourceModels: ['AttendanceSubmission'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['APPROVED'],
    excludedStatuses: ['REJECTED', 'PENDING'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  HEADCOUNT: {
    metricId: 'HEADCOUNT',
    displayName: 'Active Staff Headcount',
    description: 'Count of active employees provisioned in the workforce roster.',
    domain: 'WORKFORCE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(User.userId WHERE accountStatus == "ACTIVE")',
    sourceModels: ['User'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['ACTIVE'],
    excludedStatuses: ['DEACTIVATED', 'SUSPENDED'],
    dependencies: [],
    timeBasis: 'SNAPSHOT',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  SCHEDULED_HOURS: {
    metricId: 'SCHEDULED_HOURS',
    displayName: 'Scheduled Shift Hours',
    description: 'Total planned shift hours published in authoritative rosters.',
    domain: 'WORKFORCE',
    unit: 'HOURS',
    format: 'DURATION_HOURS',
    source: 'SUM(ShiftRoster.assignments.durationMinutes) / 60',
    sourceModels: ['ShiftRoster'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'FORECAST',
    metricType: 'PLAN',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE', 'SHIFT'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['PUBLISHED', 'LOCKED'],
    excludedStatuses: ['DRAFT', 'ARCHIVED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  HOURS_VARIANCE: {
    metricId: 'HOURS_VARIANCE',
    displayName: 'Labour Hours Variance',
    description: 'Variance between actual worked hours and scheduled roster hours.',
    domain: 'WORKFORCE',
    unit: 'HOURS',
    format: 'DURATION_HOURS',
    source: 'LABOUR_HOURS - SCHEDULED_HOURS',
    sourceModels: ['Attendance', 'ShiftRoster'],
    formulaVersion: '1.0.0',
    calculationType: 'DIFFERENCE',
    actuality: 'ACTUAL',
    metricType: 'VARIANCE',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'VERIFIED'],
    excludedStatuses: [],
    dependencies: ['LABOUR_HOURS', 'SCHEDULED_HOURS'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LATE_ARRIVAL_COUNT: {
    metricId: 'LATE_ARRIVAL_COUNT',
    displayName: 'Late Arrival Incidents',
    description: 'Count of attendance check-in punches recorded after scheduled start plus shift grace period.',
    domain: 'WORKFORCE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Attendance.isLate == true)',
    sourceModels: ['Attendance'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'VERIFIED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  EARLY_EXIT_COUNT: {
    metricId: 'EARLY_EXIT_COUNT',
    displayName: 'Early Exit Incidents',
    description: 'Count of attendance check-out punches recorded before scheduled shift end minus grace period.',
    domain: 'WORKFORCE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Attendance.isEarlyExit == true)',
    sourceModels: ['Attendance'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'VERIFIED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  NO_SHOW_COUNT: {
    metricId: 'NO_SHOW_COUNT',
    displayName: 'No-Show Shift Count',
    description: 'Count of scheduled roster shifts with no attendance punch and no approved leave request.',
    domain: 'WORKFORCE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(ScheduledShifts without Attendance and without ApprovedLeave)',
    sourceModels: ['ShiftRoster', 'Attendance', 'LeaveRequest'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: [],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LEAVE_DAYS_APPROVED: {
    metricId: 'LEAVE_DAYS_APPROVED',
    displayName: 'Approved Leave Days',
    description: 'Cumulative sanctioned leave days across approved employee leave requests in the period.',
    domain: 'WORKFORCE',
    unit: 'DAYS',
    format: 'DECIMAL_1DP',
    source: 'SUM(LeaveRequest.requestedDays WHERE status == "APPROVED")',
    sourceModels: ['LeaveRequest'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'CAFE', 'ROLE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['APPROVED'],
    excludedStatuses: ['PENDING', 'REJECTED', 'CANCELLED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  // ─── 5. CUSTOMER DOMAIN ────────────────────────────────────────────────────
  UNIQUE_CUSTOMERS: {
    metricId: 'UNIQUE_CUSTOMERS',
    displayName: 'Unique Transacting Customers',
    description: 'Count of distinct customer profiles or phone numbers identified on completed bills.',
    domain: 'CUSTOMER',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(DISTINCT Bill.customerPhone || Customer.customerId)',
    sourceModels: ['Bill', 'Customer'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['DATE', 'BUSINESS_DATE', 'CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  RETURNING_CUSTOMERS: {
    metricId: 'RETURNING_CUSTOMERS',
    displayName: 'Repeat / Returning Customer Count',
    description: 'Count of transacting guests with at least one prior completed purchase history.',
    domain: 'CUSTOMER',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Customer.customerId WHERE totalVisits > 1)',
    sourceModels: ['Customer'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['ACTIVE'],
    excludedStatuses: ['INACTIVE'],
    dependencies: [],
    timeBasis: 'SNAPSHOT',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'PARTIAL_SOURCE',
  },

  AVERAGE_CUSTOMER_SPEND: {
    metricId: 'AVERAGE_CUSTOMER_SPEND',
    displayName: 'Average Customer Spend (LTV Snapshot)',
    description: 'Net sales revenue divided by unique customer count across the period.',
    domain: 'CUSTOMER',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES / UNIQUE_CUSTOMERS',
    sourceModels: ['Bill', 'Customer'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: ['NET_SALES', 'UNIQUE_CUSTOMERS'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  // ── PM-02H Customer, POS, Order & Service Intelligence Metrics ─────────────

  IDENTIFIED_CUSTOMERS: {
    metricId: 'IDENTIFIED_CUSTOMERS',
    displayName: 'Identified Transacting Customers',
    description: 'Count of distinct identified customer profiles transacting in the reporting period.',
    domain: 'CUSTOMER',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(DISTINCT Bill.customerPhone WHERE customerPhone IS NOT NULL)',
    sourceModels: ['Customer', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  NEW_CUSTOMERS: {
    metricId: 'NEW_CUSTOMERS',
    displayName: 'New First-Time Customers',
    description: 'Identified customers whose first qualifying transaction occurs within the reporting period.',
    domain: 'CUSTOMER',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Customer WHERE firstVisitAt IN [dateFrom, dateTo])',
    sourceModels: ['Customer', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['ACTIVE', 'COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  REPEAT_CUSTOMERS: {
    metricId: 'REPEAT_CUSTOMERS',
    displayName: 'Repeat Transacting Customers',
    description: 'Identified customers with two or more lifetime visits who transacted during the period.',
    domain: 'CUSTOMER',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Customer WHERE totalVisits >= 2 AND transactedInPeriod)',
    sourceModels: ['Customer', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['ACTIVE', 'COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  CUSTOMER_VISITS: {
    metricId: 'CUSTOMER_VISITS',
    displayName: 'Total Customer Visits',
    description: 'Unique customer presence on a business date at a café (same-day multiple orders = 1 visit).',
    domain: 'CUSTOMER',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(DISTINCT customerId + businessDate + cafeId)',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  REPEAT_VISIT_RATE: {
    metricId: 'REPEAT_VISIT_RATE',
    displayName: 'Repeat Visit Rate',
    description: 'Percentage of active identified transacting customers with repeat visits.',
    domain: 'CUSTOMER',
    unit: 'PERCENTAGE',
    format: 'PERCENT',
    source: '(REPEAT_CUSTOMERS / IDENTIFIED_CUSTOMERS) * 100',
    sourceModels: ['Customer', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: ['REPEAT_CUSTOMERS', 'IDENTIFIED_CUSTOMERS'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  GUEST_COUNT: {
    metricId: 'GUEST_COUNT',
    displayName: 'Guest Covers Count',
    description: 'Total guest covers recorded on dining checks (strictly separated from Check and Customer count).',
    domain: 'SERVICE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'SUM(Bill.guestCovers WHERE serviceMode == DINE_IN)',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE', 'SERVICE_MODE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED', 'PARTIALLY_REFUNDED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  AVERAGE_SPEND_PER_GUEST: {
    metricId: 'AVERAGE_SPEND_PER_GUEST',
    displayName: 'Average Spend per Guest Cover',
    description: 'Net sales revenue divided by authoritative guest cover count (zero-safe).',
    domain: 'SERVICE',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES / GUEST_COUNT',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'SERVICE_MODE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: ['NET_SALES', 'GUEST_COUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  AVERAGE_CHECK: {
    metricId: 'AVERAGE_CHECK',
    displayName: 'Average Check / Ticket Size',
    description: 'Net sales revenue divided by total completed bill / check count.',
    domain: 'COMMERCIAL',
    unit: 'INR_PAISE',
    format: 'CURRENCY_INR',
    source: 'NET_SALES / ORDER_COUNT',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE', 'SERVICE_MODE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: ['NET_SALES', 'ORDER_COUNT'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LOYALTY_MEMBERS: {
    metricId: 'LOYALTY_MEMBERS',
    displayName: 'Total Enrolled Loyalty Members',
    description: 'Total active registered customers enrolled in the loyalty programme.',
    domain: 'LOYALTY',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Customer WHERE loyaltyStatus == ACTIVE)',
    sourceModels: ['Customer'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['ACTIVE'],
    excludedStatuses: ['CLOSED'],
    dependencies: [],
    timeBasis: 'SNAPSHOT',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  ACTIVE_LOYALTY_MEMBERS: {
    metricId: 'ACTIVE_LOYALTY_MEMBERS',
    displayName: 'Active Transacting Loyalty Members',
    description: 'Loyalty members who transacted or accrued/redeemed points in the reporting period.',
    domain: 'LOYALTY',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(DISTINCT LoyaltyLedger.customerId IN period)',
    sourceModels: ['LoyaltyLedger'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LOYALTY_POINTS_EARNED: {
    metricId: 'LOYALTY_POINTS_EARNED',
    displayName: 'Loyalty Points Earned',
    description: 'Total loyalty points accrued by members from eligible purchases and promotions.',
    domain: 'LOYALTY',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'SUM(LoyaltyLedger.pointsDelta WHERE transactionType IN [PURCHASE_ACCRUAL, PROMOTION_BONUS])',
    sourceModels: ['LoyaltyLedger'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LOYALTY_POINTS_REDEEMED: {
    metricId: 'LOYALTY_POINTS_REDEEMED',
    displayName: 'Loyalty Points Redeemed',
    description: 'Total loyalty points redeemed by members for rewards and discounts.',
    domain: 'LOYALTY',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'SUM(ABS(LoyaltyLedger.pointsDelta) WHERE transactionType == REWARD_REDEEMED)',
    sourceModels: ['LoyaltyLedger'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  FEEDBACK_COUNT: {
    metricId: 'FEEDBACK_COUNT',
    displayName: 'Customer Feedback Volume',
    description: 'Total number of customer feedback submissions recorded in the period.',
    domain: 'SERVICE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(CustomerFeedback)',
    sourceModels: ['CustomerFeedback'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'FEEDBACK_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['NEW', 'ACKNOWLEDGED', 'UNDER_REVIEW', 'RESOLVED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  AVERAGE_FEEDBACK_RATING: {
    metricId: 'AVERAGE_FEEDBACK_RATING',
    displayName: 'Average Guest Feedback Rating',
    description: 'Arithmetic mean of customer feedback ratings (1.00 to 5.00 stars).',
    domain: 'SERVICE',
    unit: 'RATIO',
    format: 'DECIMAL_2',
    source: 'AVG(CustomerFeedback.rating)',
    sourceModels: ['CustomerFeedback'],
    formulaVersion: '1.0.0',
    calculationType: 'AVERAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'FEEDBACK_CATEGORY'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['NEW', 'ACKNOWLEDGED', 'UNDER_REVIEW', 'RESOLVED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  KITCHEN_PREP_TIME_SECONDS: {
    metricId: 'KITCHEN_PREP_TIME_SECONDS',
    displayName: 'Mean Kitchen Prep Duration',
    description: 'Mean duration in seconds from KDS ticket receipt to kitchen completion.',
    domain: 'SERVICE',
    unit: 'DURATION_SECONDS',
    format: 'INTEGER',
    source: 'AVG(KdsTicket.completedAt - KdsTicket.receivedAt)',
    sourceModels: ['KdsTicket'],
    formulaVersion: '1.0.0',
    calculationType: 'AVERAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'PREP_STATION'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'COLLECTED'],
    excludedStatuses: ['CANCELLED', 'VOIDED'],
    dependencies: [],
    timeBasis: 'TIMESTAMP_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  SERVICE_SPEED_MEDIAN_SECONDS: {
    metricId: 'SERVICE_SPEED_MEDIAN_SECONDS',
    displayName: 'Median (P50) Kitchen Prep Duration',
    description: '50th percentile prep duration in seconds across completed KDS tickets.',
    domain: 'SERVICE',
    unit: 'DURATION_SECONDS',
    format: 'INTEGER',
    source: 'MEDIAN(KdsTicket.completedAt - KdsTicket.receivedAt)',
    sourceModels: ['KdsTicket'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTILE_50',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'PREP_STATION'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'COLLECTED'],
    excludedStatuses: ['CANCELLED', 'VOIDED'],
    dependencies: [],
    timeBasis: 'TIMESTAMP_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  VOID_COUNT: {
    metricId: 'VOID_COUNT',
    displayName: 'Voided Bill Count',
    description: 'Count of audited voided bills cancelled after order placement.',
    domain: 'POS_CONTROL',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Bill WHERE status == VOIDED)',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE', 'OPERATOR'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['VOIDED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  COMPLIMENTARY_COUNT: {
    metricId: 'COMPLIMENTARY_COUNT',
    displayName: 'Complimentary Bill Count',
    description: 'Count of orders completed with 100% complimentary/comp status.',
    domain: 'POS_CONTROL',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Bill WHERE paymentMethod == COMPLIMENTARY)',
    sourceModels: ['Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'ACTUAL',
    ownerDomain: 'COMMERCIAL',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE', 'OPERATOR'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED'],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  POS_EXCEPTION_COUNT: {
    metricId: 'POS_EXCEPTION_COUNT',
    displayName: 'POS Exception Event Count',
    description: 'Combined total of audited voids, high discounts, reprints, offline replays, and cash variances.',
    domain: 'POS_CONTROL',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'COUNT(Voids + HighDiscounts + Reprints + OfflineReplays + CashVariances)',
    sourceModels: ['Bill', 'RegisterSession'],
    formulaVersion: '1.0.0',
    calculationType: 'SUM',
    actuality: 'ACTUAL',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'BUSINESS_DATE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD'],
    includedStatuses: ['COMPLETED', 'VOIDED'],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  // ─── PM-02G WORKFORCE METRICS ────────────────────────────────────────────────

  ACTIVE_HEADCOUNT: {
    metricId: 'ACTIVE_HEADCOUNT',
    displayName: 'Active Staff Headcount',
    description: 'Count of distinct active employee records with at least one approved payroll entry or shift session in the reporting period. Does not double-count employees appearing in multiple periods.',
    domain: 'WORKFORCE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'Payslip.employeeId (DISTINCT) || PayrollRun.employeeId (DISTINCT)',
    sourceModels: ['Payslip', 'PayrollRun', 'Employee'],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT_DISTINCT',
    actuality: 'ACTUAL',
    ownerDomain: 'PEOPLE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE', 'ROLE', 'SHIFT'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR'],
    includedStatuses: ['APPROVED', 'PAID', 'ISSUED'],
    excludedStatuses: ['DRAFT', 'REJECTED', 'CANCELLED'],
    dependencies: [],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'ZERO_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  LABOUR_COST_PCT_OF_SALES: {
    metricId: 'LABOUR_COST_PCT_OF_SALES',
    displayName: 'Labour Cost as % of Net Sales',
    description: 'Gross employee payroll as a percentage of net sales revenue in the same period. Provides a normalized efficiency ratio for staffing cost management. Calculated as (LABOUR_COST / NET_SALES) × 100. Incomplete as full economic labour cost because employer statutory contributions are excluded.',
    domain: 'PROFITABILITY',
    unit: 'PERCENT',
    format: 'PERCENT_1DP',
    source: '(PayrollRun.totalGrossPaise / Bill.totalNetSalesPaise) * 100',
    sourceModels: ['PayrollRun', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'FINANCE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_PERIOD', 'PRIOR_YEAR', 'BUDGET'],
    includedStatuses: [],
    excludedStatuses: [],
    dependencies: ['LABOUR_COST', 'NET_SALES'],
    timeBasis: 'FISCAL_PERIOD',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  NPS_SCORE: {
    metricId: 'NPS_SCORE',

    displayName: 'Net Promoter Score (NPS)',
    description: 'Net Promoter Score unavailable — no 0–10 standard NPS question exists in customer feedback schema.',
    domain: 'SERVICE',
    unit: 'SCORE',
    format: 'INTEGER',
    source: 'UNAVAILABLE',
    sourceModels: ['CustomerFeedback'],
    formulaVersion: '1.0.0',
    calculationType: 'SCORE',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: [],
    includedStatuses: [],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  RESERVATION_COUNT: {
    metricId: 'RESERVATION_COUNT',
    displayName: 'Dining Table Reservations',
    description: 'Table reservations unavailable — no dining reservation model exists in production backend.',
    domain: 'SERVICE',
    unit: 'COUNT',
    format: 'INTEGER',
    source: 'UNAVAILABLE',
    sourceModels: [],
    formulaVersion: '1.0.0',
    calculationType: 'COUNT',
    actuality: 'UNAVAILABLE',
    ownerDomain: 'OPERATIONS',
    classification: 'INTERNAL',
    trustStatus: 'DATA_ISSUE',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: [],
    includedStatuses: [],
    excludedStatuses: [],
    dependencies: [],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'UNAVAILABLE',
  },

  // ─── 14. MULTI-CAFÉ BENCHMARKING & PORTFOLIO DOMAIN ──────────────────────────
  SAME_STORE_SALES_GROWTH: {
    metricId: 'SAME_STORE_SALES_GROWTH',
    displayName: 'Like-for-Like (Same-Store) Sales Growth %',
    description: 'Percentage variation in Net Sales between current and prior year for mature locations operating >= 12 months.',
    domain: 'MULTI_CAFE',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '((NET_SALES_MATURE_CURRENT - NET_SALES_MATURE_PRIOR) / NET_SALES_MATURE_PRIOR) * 100',
    sourceModels: ['Cafe', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'PERCENTAGE',
    actuality: 'ACTUAL',
    ownerDomain: 'EXECUTIVE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION', 'CAFE'],
    supportedComparisons: ['PRIOR_YEAR'],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED', 'REFUNDED'],
    dependencies: ['NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  PORTFOLIO_NET_SALES_SHARE: {
    metricId: 'PORTFOLIO_NET_SALES_SHARE',
    displayName: 'Portfolio Net Sales Contribution %',
    description: 'Factual percentage share of total organization net sales contributed by an individual branch.',
    domain: 'MULTI_CAFE',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(CAFE_NET_SALES / PORTFOLIO_NET_SALES) * 100',
    sourceModels: ['Cafe', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'EXECUTIVE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION'],
    supportedComparisons: [],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED', 'REFUNDED'],
    dependencies: ['NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  CAFE_NET_SALES_RANK: {
    metricId: 'CAFE_NET_SALES_RANK',
    displayName: 'Café Net Sales Rank',
    description: 'Standard competition ranking ("1224") of branches based on factual Net Sales.',
    domain: 'MULTI_CAFE',
    unit: 'RANK',
    format: 'INTEGER',
    source: 'RANK(NET_SALES, HIGH_TO_LOW)',
    sourceModels: ['Cafe', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RANK',
    actuality: 'ACTUAL',
    ownerDomain: 'EXECUTIVE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION'],
    supportedComparisons: [],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED', 'REFUNDED'],
    dependencies: ['NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  CAFE_SPLH_RANK: {
    metricId: 'CAFE_SPLH_RANK',
    displayName: 'Café SPLH Rank',
    description: 'Standard competition ranking ("1224") of branches based on Sales Per Labour Hour.',
    domain: 'MULTI_CAFE',
    unit: 'RANK',
    format: 'INTEGER',
    source: 'RANK(SPLH, HIGH_TO_LOW)',
    sourceModels: ['Cafe', 'Bill', 'PayrollRun'],
    formulaVersion: '1.0.0',
    calculationType: 'RANK',
    actuality: 'ACTUAL',
    ownerDomain: 'EXECUTIVE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION'],
    supportedComparisons: [],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED', 'REFUNDED'],
    dependencies: ['SPLH'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },

  PORTFOLIO_CONCENTRATION_TOP3: {
    metricId: 'PORTFOLIO_CONCENTRATION_TOP3',
    displayName: 'Top 3 Cafés Sales Share %',
    description: 'Combined revenue contribution share of the top 3 trading locations.',
    domain: 'MULTI_CAFE',
    unit: 'PERCENT',
    format: 'PERCENTAGE_1DP',
    source: '(SUM(TOP_3_CAFE_NET_SALES) / PORTFOLIO_NET_SALES) * 100',
    sourceModels: ['Cafe', 'Bill'],
    formulaVersion: '1.0.0',
    calculationType: 'RATIO',
    actuality: 'ACTUAL',
    ownerDomain: 'EXECUTIVE',
    classification: 'CONFIDENTIAL',
    trustStatus: 'OPERATIONAL',
    supportedDimensions: ['CAFE'],
    supportedScopes: ['ORGANISATION'],
    supportedComparisons: [],
    includedStatuses: ['COMPLETED'],
    excludedStatuses: ['VOIDED', 'REFUNDED'],
    dependencies: ['NET_SALES'],
    timeBasis: 'BUSINESS_DATE_IST',
    nullPolicy: 'NULL_IF_EMPTY',
    zeroPolicy: 'ZERO_IS_MEANINGFUL',
    availability: 'READY',
  },
};

class MetricRegistry {
  /**
   * Retrieves a metric definition by ID.
   * @param {string} metricId
   * @returns {object|null}
   */
  static getMetric(metricId) {
    if (!metricId) return null;
    return CANONICAL_METRICS[String(metricId).toUpperCase()] || null;
  }

  /**
   * Checks if a metric ID is valid and registered.
   * @param {string} metricId
   * @returns {boolean}
   */
  static isValidMetric(metricId) {
    return Boolean(MetricRegistry.getMetric(metricId));
  }

  /**
   * Returns all canonical metrics.
   * @returns {Array<object>}
   */
  static getAllMetrics() {
    return Object.values(CANONICAL_METRICS);
  }

  /**
   * Returns metrics filtered by domain.
   * @param {string} domain
   * @returns {Array<object>}
   */
  static getMetricsByDomain(domain) {
    const d = String(domain || '').toUpperCase();
    return MetricRegistry.getAllMetrics().filter((m) => m.domain === d);
  }

  /**
   * Returns metrics that are production-ready.
   * @returns {Array<object>}
   */
  static getReadyMetrics() {
    return MetricRegistry.getAllMetrics().filter((m) => m.availability === 'READY');
  }

  /**
   * Returns metrics with unavailable or incomplete sources.
   * @returns {Array<object>}
   */
  static getUnavailableOrPartialMetrics() {
    return MetricRegistry.getAllMetrics().filter((m) => m.availability !== 'READY');
  }

  /**
   * Validates an array or comma-separated list of metric IDs.
   * @param {string|string[]} metrics
   * @returns {{ valid: boolean, metrics: string[], invalid: string[] }}
   */
  static validateMetrics(metrics) {
    if (!metrics) return { valid: true, metrics: [], invalid: [] };
    const raw = Array.isArray(metrics) ? metrics : String(metrics).split(',').map((s) => s.trim());
    const validMetrics = [];
    const invalid = [];

    for (const m of raw) {
      if (!m) continue;
      const upper = m.toUpperCase();
      if (MetricRegistry.isValidMetric(upper)) {
        validMetrics.push(upper);
      } else {
        invalid.push(m);
      }
    }

    return {
      valid: invalid.length === 0,
      metrics: validMetrics,
      invalid,
    };
  }

  /**
   * Resolves a metric's effective actuality, trust status, and availability based on dependency propagation.
   * Enforces invariant: If any required dependency is UNAVAILABLE, dependent metric is marked UNAVAILABLE / DATA_ISSUE.
   * @param {string} metricId
   * @param {Record<string, string>} [sourceStates={}] - Optional map of metricId -> actuality ('ACTUAL' | 'UNAVAILABLE' etc.)
   * @returns {{ metricId: string, actuality: string, trustStatus: string, availability: string, unavailableDependencies: string[] }|null}
   */
  static resolveMetricActuality(metricId, sourceStates = {}) {
    const metric = MetricRegistry.getMetric(metricId);
    if (!metric) return null;

    const unavailableDependencies = [];
    const dependencies = Array.isArray(metric.dependencies) ? metric.dependencies : [];

    for (const depId of dependencies) {
      const depState = sourceStates[depId];
      const depActuality = (typeof depState === 'object' && depState !== null)
        ? (depState.actuality || depState.status)
        : depState;

      const depDef = MetricRegistry.getMetric(depId);
      const isUnavailable = depActuality
        ? depActuality === 'UNAVAILABLE'
        : (depDef && (depDef.actuality === 'UNAVAILABLE' || depDef.availability === 'UNAVAILABLE'));

      if (isUnavailable) {
        unavailableDependencies.push(depId);
      }
    }

    if (unavailableDependencies.length > 0 || metric.actuality === 'UNAVAILABLE') {
      return {
        metricId: metric.metricId,
        actuality: 'UNAVAILABLE',
        trustStatus: 'DATA_ISSUE',
        availability: 'UNAVAILABLE',
        unavailableDependencies,
        missingDependencies: unavailableDependencies,
      };
    }

    // If any source input is ESTIMATED, dependent resolved actuality is ESTIMATED
    let isEstimated = metric.actuality === 'ESTIMATED';
    for (const depId of dependencies) {
      const depState = sourceStates[depId];
      const depActuality = (typeof depState === 'object' && depState !== null)
        ? (depState.actuality || depState.status)
        : depState;
      if (depActuality === 'ESTIMATED') {
        isEstimated = true;
      }
    }

    return {
      metricId: metric.metricId,
      actuality: isEstimated ? 'ESTIMATED' : metric.actuality,
      trustStatus: metric.trustStatus,
      availability: metric.availability,
      unavailableDependencies: [],
      missingDependencies: [],
    };
  }

  /**
   * Returns direct dependencies for a given metric.
   * @param {string} metricId
   * @returns {string[]}
   */
  static getDependencies(metricId) {
    const metric = MetricRegistry.getMetric(metricId);
    return metric?.dependencies || [];
  }
}

module.exports = {
  CANONICAL_METRICS,
  MetricRegistry,
};
